language: node_js
node_js:
- '4'
branches:
  only:
  - master
script: mkdir public && npm run build
after_success:
- chmod +x ./scripts/deploy
- ./scripts/deploy
cache:
  directories:
  - node_modules
env:
  global:
  - GH_REF="github.com/eddywashere/resume.git"
  - secure: CH8/UFd6jnEwwgx7S1ed6ukVf5O12s0HuPiGWQhp7nZMJyZ2FzSWMlXyBhb0xjeV3i0mVTIL+HLA+ssbc0wc1GnzChtZzQ1Y6k9pVXwnyJ2bsOd1B4fZbE1tgO6aPIp1sRF5GIElEzrjnmgF4KYu8WhTU3jw44+/IFORkjH0DE1otlfjBOCXuJSgj8szIsAXlgvsa5QTz7Wfgb67tZeyhjLTLpemR2YKBpj+ek0PlDqLJzhH4PojlAtgcBiCqB8Gg8EEVqOuNKQzyl1sXeWo7TTbNHGQjyd3PwnLQTyRZhg5PYfza0TaW/Sb+MDifdZvNLpVlJcLzIRE7oFaZE75gP1wETN8G/hhmH93VBLlxRvi1EtAUp/SUXXoeZGnjjmLg1puXaHbIzAG3I2rkC0TNdRLwXK3yq+W8Jz6PuKYK4bLAJBsdhUrGJmvlVwKvjIsegnXUKI5DtMao9lVTlEpabTwpA7/ZK3fjlhG9t1eNdpm0OfXwyEfOF327DhRSBDQnPCFO7NSkiG5xwuwKuuG5bmwn9Ce3t1hP76eUQXEIukb98ouCVkxlrBn8pcEWZOkwE5Z7PdJ7MrjKqYtJPMQeI79mXqtM8l1pfxYmEq8cufnVbQWJUwFa+D80v0Ueaqu4uWxFbC47d+XIYCPmIKMp6f4agkeFHDQPPh3MuGQodw=
sudo: false
